<?php
namespace app\components\desktop;


use app\models\fitness\FitnessInfo;
use app\models\fitness\UserFitness;
use yii\base\Widget;

class WClientsWFCards extends Widget
{
    public $client;
    public $card;

    private $clientWf;


    public function init()
    {
        parent::init();
        if ($this->client === null) {
            $this->client = false;
        }
    }



    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        if(!empty($this->client)){
            $fitness = new FitnessInfo(['phone'=>$this->client->phone]);
            $fitnessInfo = $fitness->getUserInfo();// json
        }
    }
}