<?php
namespace app\components\desktop;

use yii\base\Widget;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

class WSmsForm  extends Widget
{
    public $client;

    public function init()
    {
        parent::init();
        if ($this->client === null) {
            $this->client = false;
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub


        $templateSms = '';
        $templateSms .= '<form id="sms">';
        $templateSms .= Html::hiddenInput('sms[client_id]]',$this->client->id);
        $templateSms .= '<div class="form-group">';
        $templateSms .= Html::label('Текст','',['class'=>'control-label']);
        $templateSms .= Html::input('text','sms[sms]',(isset($sms)) ? $sms : '',['class'=>'form-control']);
        $templateSms .= '</div>';
        $templateSms .= '<div class="form-group">';
        $templateSms .= Html::submitButton('Сохранить смс', ['class' => 'btn btn-warning', "id"=>"savesms"]);
        $templateSms .= Html::submitButton('Сохранить и отправить смс', ['class' => 'btn btn-warning', "id"=>"sendsms"]);
        $templateSms .= '</div></form></div>';

        return $templateSms;
    }
}